version: "3.7"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=erots
      - POSTGRES_DB=loja
    volumes: 
      - pgdata:/data/postgres
  app:
    build: .
    container_name: loja
    ports: 
      - 3333:3333  
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes: 
  pgdata:
    driver: local